FROM node:13.12.0-alpine as build
WORKDIR /frontend
ENV PATH /frontend/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm ci --silent
RUN npm install axios
RUN npm install react-scripts@3.4.1 -g --silent
#COPY . ./
#RUN npm run build
RUN apk add --upgrade strace
CMD npm start
